### ISSUE TITLE
Firing function throws error

### ISSUE THREAD

**Issue by Sigmandis** [Sigmandis/Project-2-Battleship#2]
When taking coordinates to fire the program halts throwing a TypeError "string indices must be integers".

Where shall we fire Captain nemo? Give coordinate like A7 > a1
You missed
Traceback (most recent call last):
  File "battleship.py", line 95, in <module>
    Game()
  File "battleship.py", line 18, in __init__
    self.game_turn(self.player_1, self.player_2)
  File "battleship.py", line 40, in game_turn
    player_shooter.board.fire(player_shooter, player_shootee)
  File "/Users/Sigmandis/repos/Treehouse-Python/Project 2-Battleship/boards.py", line 172, in fire
    player_shootee.board.mark(ship_cord, False)
  File "/Users/Sigmandis/repos/Treehouse-Python/Project 2-Battleship/boards.py", line 176, in mark
    row, column = self.decode_coordinates(coordinates)
  File "/Users/Sigmandis/repos/Treehouse-Python/Project 2-Battleship/boards.py", line 124, in decode_coordinates
    column = self.COLUMNS[coordinates[0]]
TypeError: string indices must be integers

**Comment by Sigmandis** [comment]
Fixed!
